name       : plasma-sdk
version    : 5.21.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/plasma-sdk-5.21.3.tar.xz : 9c20dec0545a5d1bb4e362b5778acbf2a1e65dabc7f9c07b9c84a155e4594b2b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktexteditor-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
