name       : plasma-sdk
version    : 5.16.5
release    : 23
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/plasma-sdk-5.16.5.tar.xz : 1b05f0501309099f241ebae857c24b31bc4e61fde8bfc33e854d3a1dd3d37385
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kservice-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
