name       : plasma-sdk
version    : 5.27.6
release    : 71
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.6/plasma-sdk-5.27.6.tar.xz : e352ecfecf47dd3d6f2daf2cb0729d0480145cbbf668b88d41cab425af8f76bf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktexteditor-devel
    - plasma-framework-devel
setup      : |
    rm -fr $workdir/po/nl/docs/plasma-sdk
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
