name       : plasma-sdk
version    : 5.16.3
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/plasma-sdk-5.16.3.tar.xz : 53a5d03d83ae974032fc32414003038a1b068766eba01e831ecdb1fd91df5b15
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kservice-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
