name       : plasma-sdk
version    : 5.20.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.1/plasma-sdk-5.20.1.tar.xz : a7ed7c58005f5eb6e58aa27b9b134c54d211b4007a92c3ee194c23e3be292936
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kservice-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
