name       : plasma-sdk
version    : 5.21.2
release    : 46
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.2/plasma-sdk-5.21.2.tar.xz : 7c321c3ffc4e27ba16ae752527e21ac005b894dd2deb5329dd30b7bc9409c721
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktexteditor-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
