name       : plasma-sdk
version    : 5.24.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/plasma-sdk-5.24.2.tar.xz : 83486883400fb837df6541f462df390b28df5d9a174a04e55e971ffe483c777b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktexteditor-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
