name       : plasma-sdk
version    : 5.13.4
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.4/plasma-sdk-5.13.4.tar.xz : ca5d8912dd4893a32f13f3c54e16ab6b2d1083536f250b678d43d188908dad8d
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kservice-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
