name       : plasma-sdk
version    : 5.23.5
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/plasma-sdk-5.23.5.tar.xz : 52d432377bb293ee264c7f521689b74111cd6e548a5e0938d0f346fc680214e8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktexteditor-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
