name       : plasma-sdk
version    : 5.27.7.1
release    : 72
source     :
    - https://download.kde.org/stable/plasma/5.27.7/plasma-sdk-5.27.7.1.tar.xz : d310a81eed68334886a7e7767bce9066c6ccb07087aa77d04b73acf41a5426a4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - ktexteditor-devel
    - plasma-framework-devel
setup      : |
    rm -fr $workdir/po/nl/docs/plasma-sdk
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
